openapi: 3.0.0
info:
  title: Teleremedio
  description: API para envio de remédios
  version: 1.0.0
servers:
  - url: http://teleremedio-dze5dxavh6awahaa.canadacentral-01.azurewebsites.net:3000
    description: Servidor nuvem
paths:

  /getjwthash:
    get:
      summary: Obtém uma hash jwt
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        '404':
          description: Mensagem não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    

components:
  schemas:
    Mensagem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        message:
          type: string
    MensagemInput:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    Error:
      type: object
      properties:
        error:
          type: string
    JWTReturn:
      type: string
      