%% Diagrama C4 - Nível de Componente
flowchart TD
    subgraph Frontend_Componentes [Frontend - Componentes]
        FC1[Componente de Cadastro]
        FC2[Componente de Solicitação]
        FC3[Componente de Acompanhamento]
        FC4[Componente de Histórico]
        FC5[Componente de Administração]
    end
    subgraph Backend_Componentes [Backend - Componentes]
        BC1[API de Usuários]
        BC2[API de Medicamentos]
        BC3[API de Pedidos]
        BC4[API de Logística]
        BC5[Integração com Serviços de Saúde]
    end

    FC1 -->|Envio de dados de cadastro| BC1
    FC2 -->|Solicitação de medicamentos| BC3
    FC3 -->|Consulta status do pedido| BC3
    FC4 -->|Consulta histórico de pedidos| BC3
    FC5 -->|Gerenciamento administrativo| BC2 & BC4
    BC1 -->|Acesso a dados de usuários| DB
    BC2 -->|Consulta e atualização de medicamentos| DB
    BC3 -->|Registro e atualização de pedidos| DB
    BC4 -->|Atualização de rotas e entregas| DB
    BC5 -->|Acesso a dados externos| Externo
